### ISSUE TITLE
Suggestion: higher fluidboxs for more throughput

### ISSUE THREAD

**Issue by Mernom** [raiguard/Factorio-FluidMustFlow#2]
The suggestion is to reduce the base area, and increase the height by the same ratio. This should improve the flow rate (testing showed that the K2 steel pipes have higher flow rate than the SE space pipes configured for the same volume, and the steel pipes incerase height instead of base area like the SE pipes)

Since the ducts are not meant to connect to normal fluid networks, this means you can go crazy with the values of the height without significant negative impact.
Also, a small bug: The underground pipe has twice the height as the other segments, leading it it not being able to be filled from them.

**Comment by raiguard** [comment]
Yeah, I intend on revisiting the fluid boxes to try and make them much less hacky. Thanks for the suggestion!

**Comment by raiguard** [comment]
Thanks for the suggestion. I have significantly reduced the base area and increased the height to compensate. This has increased throughput substantially and allowed me to remove the janky dual-connections that were there before, fixing the offset pipe still connecting bug!

![image](https://user-images.githubusercontent.com/3515394/147787052-26095b27-3aae-43c3-bcb7-c303e19122cc.png)
