### ISSUE TITLE
Bad english; offering to correct

### ISSUE THREAD

**Issue by Moonsilence** [raiguard/Factorio-FluidMustFlow#4]
### Description

Hi raiguard!

I am offering to carefully correct the several english language mistakes in this mod's default localization as well as some punctuation inconsistencies. A little extra polish would do this functionally perfect and popular mod some good, imho. I have contributed to one of your original mods localization before. What do you say?

Kind regards
Nicolas

### Reproduction

Some examples:

![image](https://user-images.githubusercontent.com/46093311/147652397-1bc57b26-b4e8-4963-89c4-38b21e5ee9e8.png)
![image](https://user-images.githubusercontent.com/46093311/147652424-07f41664-f392-4dba-8a9a-ef9934e09859.png)
![image](https://user-images.githubusercontent.com/46093311/147652448-89cdf332-6b65-4f10-9da8-97d005ef0116.png)

### Factorio version

1.1.50

### In-game username

Moonsilence

**Comment by raiguard** [comment]
Hi,

I'm actually a native English speaker myself, so once I get around to updating this mod, I'll fix the localization. Thanks for the offer though!
