### ISSUE TITLE
I have many mods that conflicting in recipes part. Could you add a checkbox to make use standard recipes for all in this mod?

### ISSUE THREAD

**Issue by danilbor11** [raiguard/Factorio-FluidMustFlow#7]
### Description

I play Sea Block with many recipes forcibly changed. And i need a setting to use standart items in all recipies in FluidMustFlow mod. 

### Reproduction

Not important. 

### Factorio version

1.1.57

### In-game username

danil_bor450

**Comment by raiguard** [comment]
Sorry, I'm not sure what you are talking about.

**Comment by danilbor11** [comment]
Fluid Must Flow uses modded items instead of default iron plates, iron gears, steel, engines and pipes. I can't craft modded items because they are disabled. I need a setting that force FMF use only "default" factorio items. Sorry for poor English, i have tried.

**Comment by raiguard** [comment]
Could you upload your save file so I can take a look?

**Comment by danilbor11** [comment]
[sand.zip](https://github.com/raiguard/Factorio-FluidMustFlow/files/8550649/sand.zip)

**Comment by danilbor11** [comment]
Should I learn modding to make my dream come true? Just do it?

**Comment by danilbor11** [comment]
Technologies of components was not learned. Because of this I was not able to craft them. It's pointless thread, sorry for loosing your time. Delete this thread please.

**Comment by raiguard** [comment]
It's no problem! Sorry for not taking a look at this sooner - my life has been very busy recently.
